name: Docker

#on:
#  push:
#    branches:
#      - 'main'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: |-
          docker build . --file Dockerfile --tag product-service:$(date +%s)
      - name: Push Docker Image
        run: |-
          docker push codeninjas23/product-service:$(date +%s)